{{- $root := . }}
{{- if .Values.akka.http.enabled -}}
{{- range $i, $ingress := .Values.akka.http.ingresses }}
{{- $fullName := include "akka.fullname" $root -}}
{{- $svcPort := $ingress.targetPort }}
{{- $apiVersion := include "akka.ingress.apiVersion" $root }}
---
apiVersion: "{{ $apiVersion }}"
kind: Ingress
metadata:
  annotations:
    {{- toYaml $ingress.annotations | nindent 4 }}
  labels:
    {{- include "akka.labels" $root | nindent 4 }}
    {{- with $ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: "{{ $fullName }}{{ with $ingress.name }}-{{ . }}{{ end }}"
spec:
  {{- if $ingress.ingressClassName }}
  ingressClassName: {{ $ingress.ingressClassName }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: "{{ .secretName }}"
    {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: "{{ .host }}"
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            {{- if eq $apiVersion "networking.k8s.io/v1" }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if eq $apiVersion "networking.k8s.io/v1" }}
              service:
                name: "{{ $fullName }}"
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: "{{ $fullName }}"
              servicePort: {{ $svcPort }}
              {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
